apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
type: Opaque
data:
  username: {{ .Values.secrets.dbUser | b64enc }}
  password: {{ .Values.secrets.dbPassword | b64enc }}
  dbname: {{ .Values.secrets.dbName | b64enc }}
